project:
  type: website
  output-dir: docs

website:
  title: "Nicholas Chang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - research.qmd
       - current_projects.qmd
       - past_projects.qmd
    tools: 
      - icon: github
        href: https://github.com/tuataratuatarae

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

